// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    usersTable,
    mealsTable,
    foodsTable,
    diningHallFoodsTable,
    diningHallsTable,
  ];
  late final Shape0 usersTable = Shape0(
    source: i0.VersionedTable(
      entityName: 'users_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 mealsTable = Shape1(
    source: i0.VersionedTable(
      entityName: 'meals_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_14,
        _column_15,
        _column_16,
        _column_2,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 foodsTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'foods_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_26,
        _column_2,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_25,
        _column_23,
        _column_36,
        _column_37,
        _column_38,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 diningHallFoodsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'dining_hall_foods_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_39,
        _column_15,
        _column_16,
        _column_40,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 diningHallsTable = Shape4(
    source: i0.VersionedTable(
      entityName: 'dining_halls_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_41, _column_2, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get useDietary =>
      columnsByName['use_dietary']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get useMealPlanning =>
      columnsByName['use_meal_planning']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get gender =>
      columnsByName['gender']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get age =>
      columnsByName['age']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get weight =>
      columnsByName['weight']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get goal =>
      columnsByName['goal']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dietaryRestrictions =>
      columnsByName['dietary_restrictions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealPlan =>
      columnsByName['meal_plan']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get diningCourtRanking =>
      columnsByName['dining_court_ranking']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get macros =>
      columnsByName['macros']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'PRIMARY KEY AUTOINCREMENT',
      ),
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'uid',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_3(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'use_dietary',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("use_dietary" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<bool> _column_4(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'use_meal_planning',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("use_meal_planning" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gender',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'age',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'weight',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'height',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'goal',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dietary_restrictions',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meal_plan',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dining_court_ranking',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'macros',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get diningCourt =>
      columnsByName['dining_court']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealTime =>
      columnsByName['meal_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get foodItems =>
      columnsByName['food_items']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get totalCalories =>
      columnsByName['total_calories']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalProtein =>
      columnsByName['total_protein']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get mealId =>
      columnsByName['meal_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get totalCarbs =>
      columnsByName['total_carbs']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalFats =>
      columnsByName['total_fats']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<bool> get isFavorited =>
      columnsByName['is_favorited']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isAIMeal =>
      columnsByName['is_a_i_meal']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get lastUpdated =>
      columnsByName['last_updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dining_court',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meal_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'food_items',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_18(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_calories',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_19(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_protein',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meal_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_21(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_carbs',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_22(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_fats',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<bool> _column_23(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'is_favorited',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("is_favorited" IN (0, 1))',
      ),
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<bool> _column_24(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'is_a_i_meal',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("is_a_i_meal" IN (0, 1))',
      ),
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_updated',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get calories =>
      columnsByName['calories']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get protein =>
      columnsByName['protein']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbs =>
      columnsByName['carbs']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fats =>
      columnsByName['fats']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sugar =>
      columnsByName['sugar']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get labels =>
      columnsByName['labels']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ingredients =>
      columnsByName['ingredients']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get station =>
      columnsByName['station']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get collection =>
      columnsByName['collection']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastUpdated =>
      columnsByName['last_updated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get isFavorited =>
      columnsByName['is_favorited']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get servingSize =>
      columnsByName['serving_size']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get saturatedFat =>
      columnsByName['saturated_fat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get addedSugars =>
      columnsByName['added_sugars']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'food_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_27(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'calories',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_28(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'protein',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_29(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'carbs',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_30(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fats',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sugar',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'labels',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ingredients',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'station',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'collection',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'serving_size',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_37(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'saturated_fat',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'added_sugars',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get diningHall =>
      columnsByName['dining_hall']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealTime =>
      columnsByName['meal_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get miniFood =>
      columnsByName['mini_food']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastUpdated =>
      columnsByName['last_updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dining_hall',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mini_food',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get diningHallId =>
      columnsByName['dining_hall_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get schedule =>
      columnsByName['schedule']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dining_hall_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'schedule',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    usersTable,
    mealsTable,
    foodsTable,
    diningHallFoodsTable,
    diningHallsTable,
  ];
  late final Shape5 usersTable = Shape5(
    source: i0.VersionedTable(
      entityName: 'users_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_43,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 mealsTable = Shape1(
    source: i0.VersionedTable(
      entityName: 'meals_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_14,
        _column_15,
        _column_16,
        _column_2,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 foodsTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'foods_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_26,
        _column_2,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_25,
        _column_23,
        _column_36,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 diningHallFoodsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'dining_hall_foods_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_39,
        _column_15,
        _column_16,
        _column_40,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 diningHallsTable = Shape4(
    source: i0.VersionedTable(
      entityName: 'dining_halls_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_41, _column_2, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get useDietary =>
      columnsByName['use_dietary']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get useMealPlanning =>
      columnsByName['use_meal_planning']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get gender =>
      columnsByName['gender']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get age =>
      columnsByName['age']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get weight =>
      columnsByName['weight']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get goal =>
      columnsByName['goal']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dietaryRestrictions =>
      columnsByName['dietary_restrictions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealPlan =>
      columnsByName['meal_plan']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get diningCourtRanking =>
      columnsByName['dining_court_ranking']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get macros =>
      columnsByName['macros']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get mealsPerDay =>
      columnsByName['meals_per_day']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'meals_per_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('2'),
    );
i1.GeneratedColumn<double> _column_44(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'saturated_fat',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_45(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'added_sugars',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    usersTable,
    mealsTable,
    foodsTable,
    diningHallFoodsTable,
    diningHallsTable,
  ];
  late final Shape6 usersTable = Shape6(
    source: i0.VersionedTable(
      entityName: 'users_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_43,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 mealsTable = Shape1(
    source: i0.VersionedTable(
      entityName: 'meals_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_14,
        _column_15,
        _column_16,
        _column_2,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 foodsTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'foods_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_26,
        _column_2,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_25,
        _column_23,
        _column_36,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 diningHallFoodsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'dining_hall_foods_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_39,
        _column_15,
        _column_16,
        _column_40,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 diningHallsTable = Shape4(
    source: i0.VersionedTable(
      entityName: 'dining_halls_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_41, _column_2, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get useDietary =>
      columnsByName['use_dietary']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get useMealPlanning =>
      columnsByName['use_meal_planning']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get gender =>
      columnsByName['gender']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get age =>
      columnsByName['age']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get weight =>
      columnsByName['weight']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get goal =>
      columnsByName['goal']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dietaryRestrictions =>
      columnsByName['dietary_restrictions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealPlan =>
      columnsByName['meal_plan']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get diningCourtRanking =>
      columnsByName['dining_court_ranking']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get macros =>
      columnsByName['macros']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get mealsPerDay =>
      columnsByName['meals_per_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get activityLevel =>
      columnsByName['activity_level']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'activity_level',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'sedentary\''),
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    usersTable,
    mealsTable,
    foodsTable,
    diningHallFoodsTable,
    diningHallsTable,
  ];
  late final Shape6 usersTable = Shape6(
    source: i0.VersionedTable(
      entityName: 'users_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_43,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 mealsTable = Shape7(
    source: i0.VersionedTable(
      entityName: 'meals_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_14,
        _column_15,
        _column_16,
        _column_2,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_47,
        _column_48,
        _column_49,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 foodsTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'foods_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_26,
        _column_2,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_25,
        _column_23,
        _column_36,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 diningHallFoodsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'dining_hall_foods_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_39,
        _column_15,
        _column_16,
        _column_40,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 diningHallsTable = Shape4(
    source: i0.VersionedTable(
      entityName: 'dining_halls_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_41, _column_2, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get diningCourt =>
      columnsByName['dining_court']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealTime =>
      columnsByName['meal_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get foodItems =>
      columnsByName['food_items']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get totalCalories =>
      columnsByName['total_calories']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalProtein =>
      columnsByName['total_protein']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get mealId =>
      columnsByName['meal_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get totalCarbs =>
      columnsByName['total_carbs']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalFats =>
      columnsByName['total_fats']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalSugar =>
      columnsByName['total_sugar']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalSaturatedFat =>
      columnsByName['total_saturated_fat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalAddedSugars =>
      columnsByName['total_added_sugars']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<bool> get isFavorited =>
      columnsByName['is_favorited']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isAIMeal =>
      columnsByName['is_a_i_meal']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get lastUpdated =>
      columnsByName['last_updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_47(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_sugar',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_48(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_saturated_fat',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_49(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_added_sugars',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    usersTable,
    mealsTable,
    foodsTable,
    diningHallFoodsTable,
    diningHallsTable,
  ];
  late final Shape6 usersTable = Shape6(
    source: i0.VersionedTable(
      entityName: 'users_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_43,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 mealsTable = Shape7(
    source: i0.VersionedTable(
      entityName: 'meals_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_14,
        _column_15,
        _column_16,
        _column_2,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_47,
        _column_48,
        _column_49,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 foodsTable = Shape8(
    source: i0.VersionedTable(
      entityName: 'foods_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_26,
        _column_2,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_25,
        _column_23,
        _column_36,
        _column_44,
        _column_45,
        _column_50,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 diningHallFoodsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'dining_hall_foods_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_39,
        _column_15,
        _column_16,
        _column_40,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 diningHallsTable = Shape4(
    source: i0.VersionedTable(
      entityName: 'dining_halls_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_41, _column_2, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get calories =>
      columnsByName['calories']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get protein =>
      columnsByName['protein']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbs =>
      columnsByName['carbs']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fats =>
      columnsByName['fats']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sugar =>
      columnsByName['sugar']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get labels =>
      columnsByName['labels']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ingredients =>
      columnsByName['ingredients']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get station =>
      columnsByName['station']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get collection =>
      columnsByName['collection']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastUpdated =>
      columnsByName['last_updated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get isFavorited =>
      columnsByName['is_favorited']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get servingSize =>
      columnsByName['serving_size']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get saturatedFat =>
      columnsByName['saturated_fat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get addedSugars =>
      columnsByName['added_sugars']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quantity',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('1'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
  ),
);
