// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDitTP773oFmv7qWcNc1B9QtMPpq_WwfuI',
    appId: '1:29513962283:web:b9184d26d086511bea2b6e',
    messagingSenderId: '29513962283',
    projectId: 'boilerfuel-hello-world',
    authDomain: 'boilerfuel-hello-world.firebaseapp.com',
    storageBucket: 'boilerfuel-hello-world.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp-VmtvekahyTdpou6eGJIaQrwpfFUyOc',
    appId: '1:29513962283:android:a85a61d68048563dea2b6e',
    messagingSenderId: '29513962283',
    projectId: 'boilerfuel-hello-world',
    storageBucket: 'boilerfuel-hello-world.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRQdeX00Zd7IhskqzrgtqqpnyFbG91QZs',
    appId: '1:29513962283:ios:c5000de4e9a11e7cea2b6e',
    messagingSenderId: '29513962283',
    projectId: 'boilerfuel-hello-world',
    storageBucket: 'boilerfuel-hello-world.firebasestorage.app',
    iosBundleId: 'com.example.boilerFuel',
  );
}
